---
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install: 
  - gem install bundler -v 2.1.4
  - sudo apt-get -y install nodejs npm
  - export NODE_PATH=$(npm root -g)
  - npm install -g puppeteer
